version: 2
updates:
- package-ecosystem: npm
  directory: "/builder"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/builder"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
