name: Build images

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: test build builder image
        if: github.ref != 'refs/heads/master'
        working-directory: ./builder
        run: docker build -f Dockerfile-alpine .
        
      - name: test build production image
        if: github.ref != 'refs/heads/master'
        working-directory: ./production
        run: docker build -f Dockerfile-alpine .
        
  builder_slim:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
          
      - name: Build and push slim builder image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: jiting/rails-base
          path: builder
          dockerfile: builder/Dockerfile
          tags: builder-2.7-slim-buster,builder-2.7-slim,builder-slim

  builder_alpine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push alpine builder image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: jiting/rails-base
          path: builder
          dockerfile: builder/Dockerfile-alpine
          tags: builder-2.7-alpine,builder-2.7,builder-alpine,builder-latest

  production_slim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Build and push slim production image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: jiting/rails-base
          dockerfile: production/Dockerfile
          tags: production-2.7-slim-buster,production-2.7-slim,production-slim
  
  production_alpine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push alpine production image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: jiting/rails-base
          dockerfile: production/Dockerfile-alpine
          tags: production-2.7-alpine,production-2.7,production-alpine,production-latest
