name: Build images

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test build builder image
        if: github.ref != 'refs/heads/master'
        working-directory: ./builder
        run: docker build --pull --compress -f Dockerfile-alpine .

      - name: test build production image
        if: github.ref != 'refs/heads/master'
        working-directory: ./production
        run: docker build --pull --compress -f Dockerfile-alpine .

  builder_slim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push slim builder image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: builder
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          file: builder/Dockerfile
          tags: |
            jiting/rails-base:builder-3.2.0-slim-bullseye
            jiting/rails-base:builder-3.2-slim-bullseye
            jiting/rails-base:builder-3.2-slim
            jiting/rails-base:builder-slim

  builder_alpine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push alpine builder image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: builder
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          file: builder/Dockerfile-alpine
          tags: |
            jiting/rails-base:builder-3.2.0-alpine
            jiting/rails-base:builder-3.2-alpine
            jiting/rails-base:builder-3.2.0
            jiting/rails-base:builder-3.2
            jiting/rails-base:builder-alpine
            jiting/rails-base:builder-latest


  production_slim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push slim production image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: production
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          file: production/Dockerfile
          tags: |
            jiting/rails-base:production-3.2-slim-bullseye
            jiting/rails-base:production-3.2.0-slim-bullseye
            jiting/rails-base:production-3.2-slim
            jiting/rails-base:production-slim

  production_alpine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: jiting
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push alpine production image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: production
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          file: production/Dockerfile-alpine
          tags: |
            jiting/rails-base:production-3.2.0-alpine
            jiting/rails-base:production-3.2-alpine
            jiting/rails-base:production-3.2
            jiting/rails-base:production-3.2.0
            jiting/rails-base:production-alpine
            jiting/rails-base:production-latest
